In [45]:
import numpy as np
import os
import glob

fs = [f for f in os.listdir() if '.npy' in f]

arr = np.load(fs[0], allow_pickle=True)

In [46]:
def partial_match(s, target):
    str_list = s.split('_')
    for string in str_list:
        if target in string:
            return string
    
partial_match(fs[0], 'rat')

'rat1'

In [47]:
arrs = [(f, np.load(f, allow_pickle=True)) for i, f in enumerate(fs) if 'coke' in f and 'PFC' in f]

In [52]:
def flatten(kv):
    '''
    kv is a key, value pair tuple where the value is an n by m array
    returns a new list of key value pairs where each value is a 1 by m subarray
    from the original n by m value array. 
    key is unchanged for all new key, value pairs
    '''
    key, value = kv

    return [(key, subarray) for subarray in value]

flattened_arr = []
for arr in arrs:
    f = flatten(arr)
    f = [('_'.join([partial_match(kv[0], 'Ephys'), partial_match(kv[0], 'rat'), f'trial{i}']), kv[1]) for i, kv in enumerate(f)]
    flattened_arr += f

In [53]:
len(flattened_arr)

203

In [63]:
dict(flattened_arr)

{'Ephys7_rat2_trial0': array([ -98.56989,  -94.28192,  -92.21966, ..., -128.11016, -117.90064,
        -108.78965]),
 'Ephys7_rat2_trial1': array([-117.22995, -114.38907, -111.99622, ...,  -44.61484,  -45.10473,
         -43.16077]),
 'Ephys7_rat2_trial2': array([  9.69693,  10.17047,  14.97577, ..., -15.70303, -13.21768,
        -11.65365]),
 'Ephys7_rat2_trial3': array([-147.56109, -149.04648, -150.90573, ..., -110.74414, -107.96719,
        -104.98596]),
 'Ephys7_rat2_trial4': array([-109.94373, -108.77261, -110.01798, ...,  -80.71216,  -89.0256 ,
        -102.89212]),
 'Ephys7_rat2_trial5': array([ -38.71646,  -36.02817,  -33.6044 , ..., -106.36401, -102.43649,
         -99.14654]),
 'Ephys7_rat2_trial6': array([-34.00153, -30.85703, -31.6203 , ...,  -3.39279,  -4.06372,
         -0.90131]),
 'Ephys7_rat2_trial7': array([-21.60397, -23.25351, -25.28943, ...,  21.37997,  19.56369,
         14.90796]),
 'Ephys7_rat2_trial8': array([-74.6611 , -76.22375, -78.84896, ..., -51.82675, -47

In [61]:
import itertools

treatment = {'ChABC', 'Vehicle'}
cue = {'coke', 'saline'}
region = {'PFC', 'HPC'}

for combination in itertools.product(treatment, cue, region):
    print(combination[0])

ChABC
ChABC
ChABC
ChABC
Vehicle
Vehicle
Vehicle
Vehicle


In [62]:
flattened_arr

[('Ephys7_rat2_trial0',
  array([ -98.56989,  -94.28192,  -92.21966, ..., -128.11016, -117.90064,
         -108.78965])),
 ('Ephys7_rat2_trial1',
  array([-117.22995, -114.38907, -111.99622, ...,  -44.61484,  -45.10473,
          -43.16077])),
 ('Ephys7_rat2_trial2',
  array([  9.69693,  10.17047,  14.97577, ..., -15.70303, -13.21768,
         -11.65365])),
 ('Ephys7_rat2_trial3',
  array([-147.56109, -149.04648, -150.90573, ..., -110.74414, -107.96719,
         -104.98596])),
 ('Ephys7_rat2_trial4',
  array([-109.94373, -108.77261, -110.01798, ...,  -80.71216,  -89.0256 ,
         -102.89212])),
 ('Ephys7_rat2_trial5',
  array([ -38.71646,  -36.02817,  -33.6044 , ..., -106.36401, -102.43649,
          -99.14654])),
 ('Ephys7_rat2_trial6',
  array([-34.00153, -30.85703, -31.6203 , ...,  -3.39279,  -4.06372,
          -0.90131])),
 ('Ephys7_rat2_trial7',
  array([-21.60397, -23.25351, -25.28943, ...,  21.37997,  19.56369,
          14.90796])),
 ('Ephys7_rat2_trial8',
  array([-74.6611 

In [64]:
arrs

[('Ephys7_D0B_rat2_PFC_Ch20_coke.npy',
  array([[ -98.56989,  -94.28192,  -92.21966, ..., -128.11016, -117.90064,
          -108.78965],
         [-117.22995, -114.38907, -111.99622, ...,  -44.61484,  -45.10473,
           -43.16077],
         [   9.69693,   10.17047,   14.97577, ...,  -15.70303,  -13.21768,
           -11.65365],
         ...,
         [ -10.67981,  -20.12546,  -28.45908, ...,  -77.10321,  -71.61996,
           -68.35019],
         [ -89.41318,  -82.54578,  -75.83945, ...,   36.03562,   34.27877,
            32.92605],
         [  16.95227,   14.57788,    2.13791, ...,  -23.17496,  -26.36661,
           -30.50009]])),
 ('Ephys5_D0C_rat1_PFC_Ch11_coke.npy',
  array([[ 56.91351,  56.90497,  56.93805, ..., 133.01087, 139.5333 ,
          137.01676],
         [ 31.85175,  50.35254,  64.41077, ..., 177.58432, 179.40643,
          178.35037],
         [ 73.91748,  81.1471 ,  90.08252, ..., 113.2612 , 101.82709,
           85.34271],
         ...,
         [211.87246, 196.21

In [102]:
d_PFC = np.load('CUE0_aggregated/Vehicle_saline_PFC.npy', allow_pickle=True).item()
d_HPC = np.load('CUE0_aggregated/Vehicle_saline_HPC.npy', allow_pickle=True).item()

In [108]:
d_PFC

{'Ephys11_rat1_trial0': array([287.07053, 279.56775, 266.27502, ...,  52.05914,  66.08673,
         71.33398]),
 'Ephys11_rat1_trial1': array([ 34.73804,  24.4436 ,  12.81402, ..., 103.66833,  89.84787,
         82.39599]),
 'Ephys11_rat1_trial2': array([-5.23279,  4.4975 , 26.42084, ..., 69.50122, 90.39233, 89.43555]),
 'Ephys11_rat1_trial3': array([164.55445, 144.90659, 132.34628, ..., 110.97253, 108.76251,
         96.50748]),
 'Ephys11_rat1_trial4': array([ 168.33404,  160.51163,  147.78064, ..., -104.02551,  -96.3537 ,
         -92.41766]),
 'Ephys11_rat1_trial5': array([134.08468, 131.69107, 130.48547, ...,  69.57388,  63.82758,
         67.75983]),
 'Ephys11_rat1_trial6': array([137.78003, 133.47925, 133.20245, ...,  21.76111,  46.20072,
         66.37936]),
 'Ephys11_rat1_trial7': array([-134.8103 , -112.02027,  -82.25836, ...,  127.71924,  135.08612,
         132.38214]),
 'Ephys11_rat1_trial8': array([-56.65698, -68.95728, -79.9668 , ..., 226.33142, 220.92441,
        228.024

In [157]:
len(d_HPC)

147

In [82]:
keeptrialsA = [bool(n) for n in [1, 0, 0, 1, 1, 1, 0, 1, 0, 1]]
keeptrialsB = [bool(n) for n in [1, 0, 1, 0, 1, 1, 1, 1, 0, 0]]

In [90]:
sumAB = ~np.array(keeptrialsA) + ~np.array(keeptrialsB)
sumAB = ~sumAB
sumAB.astype(int)

array([1, 0, 0, 0, 1, 1, 0, 1, 0, 0])

In [176]:
d0 = dict(zip(['trial'+str(i) for i in range(len(sumAB))],[[j for j in range(i+3)] if i%2 == 0 else None for i in range(len(sumAB))]))
d1 = dict(zip(['trial'+str(i) for i in range(len(sumAB))],[[j+3 for j in range(i+3)] if i < 6 else None for i in range(len(sumAB))]))

for kv in d0.items():
    print(kv)
    
print('\n')
for kv in d1.items():
    print(kv)
    
def dictfilt(curr_d, ref_d):
    assert set(curr_d.keys()) == set(ref_d.keys())
    
    filt_d = {}
    for key in curr_d:
        if curr_d[key] is not None and ref_d[key] is not None:
            filt_d.update({key: curr_d[key]})
            
    return filt_d

dictfilt(d0, d1)

('trial0', [0, 1, 2])
('trial1', None)
('trial2', [0, 1, 2, 3, 4])
('trial3', None)
('trial4', [0, 1, 2, 3, 4, 5, 6])
('trial5', None)
('trial6', [0, 1, 2, 3, 4, 5, 6, 7, 8])
('trial7', None)
('trial8', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
('trial9', None)


('trial0', [3, 4, 5])
('trial1', [3, 4, 5, 6])
('trial2', [3, 4, 5, 6, 7])
('trial3', [3, 4, 5, 6, 7, 8])
('trial4', [3, 4, 5, 6, 7, 8, 9])
('trial5', [3, 4, 5, 6, 7, 8, 9, 10])
('trial6', None)
('trial7', None)
('trial8', None)
('trial9', None)


{'trial0': [0, 1, 2],
 'trial2': [0, 1, 2, 3, 4],
 'trial4': [0, 1, 2, 3, 4, 5, 6]}

In [171]:
d_PFC = np.load('aggregated_data/CUE1/Vehicle_coke_PFC.npy', allow_pickle=True).item()
d_HPC = np.load('aggregated_data/CUE1/Vehicle_coke_HPC.npy', allow_pickle=True).item()

print(set(d_PFC.keys()) == set(d_HPC.keys()))
print(len(d_PFC))

True
142


In [173]:
d_PFC_old = np.load('/Users/jonathanramos/Desktop/CCA NEW ANALYSES/Curating EPHYS5-11/CUE1/Vehicle/CUE1_Vehicle_coke_PFC.npy', allow_pickle=True)
print(np.shape(d_PFC_old))

(140, 4000)


In [168]:
d_PFC_old[]

array([[  65.55164,   70.98938,   68.73584, ...,  -61.55145,  -54.23242,
         -41.88611],
       [   7.59564,   15.93951,   20.03241, ...,   11.29584,   -3.57916,
         -19.63538],
       [-344.80286, -354.57991, -366.41813, ...,  906.5921 ,  905.9345 ,
         909.514  ],
       ...,
       [ 163.44486,  145.73004,  127.49737, ...,   76.28918,   67.59558,
          62.56775],
       [ 167.03442,  165.78894,  161.52582, ...,  143.4313 ,  144.67987,
         139.88308],
       [ 121.33936,  115.7933 ,  109.43586, ...,    7.79962,   -2.414  ,
          -7.14752]])

In [178]:
d_PFC = np.load('aggregated_data/CUE0/Vehicle_coke_PFC_curated.npy', allow_pickle=True).item()
d_HPC = np.load('aggregated_data/CUE0/Vehicle_coke_HPC_curated.npy', allow_pickle=True).item()

In [180]:
len(d_PFC)

117

In [181]:
len(d_HPC)

117

In [19]:
import numpy as np
import pandas as pd

df_events = pd.read_csv("/Volumes/T7/CCA_Raw_Data/CUE1/Ephys11_rat1_CUE1/Event_CUE1green_coke_rat1.csv").drop('Unnamed: 0', axis=1)
df_events

event    timestamp  timestamp_rounded       diff  test
0    reward0   604.725100              600.0  11.000000  True
1    reward1   669.721900              670.0  64.996800  True
2    reward2   699.720433              700.0  29.998533  True
3    reward3   719.719433              720.0  19.999000  True
4    reward4   738.718500              740.0  18.999067  True
..       ...          ...                ...        ...   ...
56  reward56  2385.551533             2390.0  64.991600  True
57  reward57  2415.547667             2420.0  29.996133  True
58  reward58  2435.545100             2440.0  19.997433  True
59  reward59  2454.542633             2450.0  18.997533  True
60  reward60  2476.539800             2480.0  21.997167  True

[61 rows x 5 columns]

In [21]:
df_events.timestamp[0] + 1800

2404.7251

In [22]:
df_events[df_events.timestamp <= df_events.timestamp[0] + 1800]

event    timestamp  timestamp_rounded       diff  test
0    reward0   604.725100              600.0  11.000000  True
1    reward1   669.721900              670.0  64.996800  True
2    reward2   699.720433              700.0  29.998533  True
3    reward3   719.719433              720.0  19.999000  True
4    reward4   738.718500              740.0  18.999067  True
5    reward5   760.717400              760.0  21.998900  True
6    reward6   825.714200              830.0  64.996800  True
7    reward7   855.712733              860.0  29.998533  True
8    reward8   875.711733              880.0  19.999000  True
9    reward9   894.710800              890.0  18.999067  True
10  reward10   916.709700              920.0  21.998900  True
11  reward11   981.706467              980.0  64.996767  True
12  reward12  1011.705000             1010.0  29.998533  True
13  reward13  1031.704000             1030.0  19.999000  True
14  reward14  1050.703033             1050.0  18.999033  True
15  reward15  1072.701967             1070.0  21.998933  True
16  reward16  1137.698767             1140.0  64.996800  True
17  reward17  1167.697300             1170.0  29.998533  True
18  reward18  1187.696300             1190.0  19.999000  True
19  reward19  1206.695367             1210.0  18.999067  True
20  reward20  1228.694267             1230.0  21.998900  True
21  reward21  1293.689767             1290.0  64.995500  True
22  reward22  1323.685833             1320.0  29.996067  True
23  reward23  1343.683233             1340.0  19.997400  True
24  reward24  1362.680767             1360.0  18.997533  True
25  reward25  1384.677867             1380.0  21.997100  True
26  reward26  1449.669367             1450.0  64.991500  True
27  reward27  1479.665400             1480.0  29.996033  True
28  reward28  1499.663767             1500.0  19.998367  True
29  reward29  1518.661500             1520.0  18.997733  True
30  reward30  1540.659700             1540.0  21.998200  True
31  reward31  1605.651367             1610.0  64.991667  True
32  reward32  1635.647500             1640.0  29.996133  True
33  reward33  1655.645067             1660.0  19.997567  True
34  reward34  1674.642767             1670.0  18.997700  True
35  reward35  1696.639933             1700.0  21.997167  True
36  reward36  1761.631733             1760.0  64.991800  True
37  reward37  1791.627867             1790.0  29.996133  True
38  reward38  1811.625300             1810.0  19.997433  True
39  reward39  1830.622833             1830.0  18.997533  True
40  reward40  1852.620000             1850.0  21.997167  True
41  reward41  1917.611667             1920.0  64.991667  True
42  reward42  1947.607800             1950.0  29.996133  True
43  reward43  1967.605233             1970.0  19.997433  True
44  reward44  1986.602767             1990.0  18.997533  True
45  reward45  2008.599900             2010.0  21.997133  True
46  reward46  2073.591567             2070.0  64.991667  True
47  reward47  2103.587733             2100.0  29.996167  True
48  reward48  2123.585200             2120.0  19.997467  True
49  reward49  2142.582767             2140.0  18.997567  True
50  reward50  2164.579933             2160.0  21.997167  True
51  reward51  2229.571600             2230.0  64.991667  True
52  reward52  2259.567767             2260.0  29.996167  True
53  reward53  2279.565200             2280.0  19.997433  True
54  reward54  2298.562733             2300.0  18.997533  True
55  reward55  2320.559933             2320.0  21.997200  True
56  reward56  2385.551533             2390.0  64.991600  True

In [1]:
import numpy as np 
import pandas as pd

f = np.load('Ephys11_CUE1_rat1_HPC_Ch2_saline.npy', allow_pickle=True)

In [3]:
d_PFC = np.load('aggregated_data/CUE0/Vehicle_coke_PFC_curated.npy', allow_pickle=True).item()
d_HPC = np.load('aggregated_data/CUE0/Vehicle_coke_HPC_curated.npy', allow_pickle=True).item()

(31, 4000)

In [ ]:
f = np.load('')